# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.CharField(default='Washington DC', max_length=100),
        ),
        migrations.AddField(
            model_name='traveler',
            name='location',
            field=models.CharField(default='Washington DC', max_length=100),
        ),
    ]
